server:
  port: 9090
spring:
  application:
    name: "LoanRequestService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:9090"

routes:
  paths:
    loans: "/api/v1/loans"
    loansById: "/api/v1/loans/{id}"

adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "postgres"
    schema: "service"
    username: "postgres"
    password: "postgres"

logging:
  level:
    root: INFO
    co.com.tecnohalecatez: TRACE