CREATE SCHEMA IF NOT EXISTS service AUTHORIZATION postgres;

COMMENT ON SCHEMA service IS 'service schema';

CREATE TABLE service.loans (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   amount DOUBLE PRECISION NOT NULL,
   term INTEGER NOT NULL,
   identity_document VARCHAR(100) NOT NULL,
   email VARCHAR(100),
   registration_date DATE NOT NULL,
   state_id INTEGER NOT NULL,
   type_id INTEGER NOT NULL,
   FOREIGN KEY (state_id) REFERENCES service.states (id),
   FOREIGN KEY (type_id) REFERENCES service.types (id)
);

CREATE TABLE service.types (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   min_amount DOUBLE PRECISION NOT NULL,
   max_amount DOUBLE PRECISION NOT NULL,
   interest_rate DOUBLE PRECISION NOT NULL,
   automatic_validation BOOLEAN DEFAULT FALSE
);

CREATE TABLE service.states (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   description VARCHAR(255)
);