CREATE SCHEMA IF NOT EXISTS service AUTHORIZATION postgres;

COMMENT ON SCHEMA service IS 'service schema';

CREATE TABLE service.loans (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   amount DOUBLE PRECISION NOT NULL,
   term INTEGER NOT NULL,
   identity_document VARCHAR(100) NOT NULL,
   email VARCHAR(100),
   registration_date DATE NOT NULL,
   state_id INTEGER NOT NULL,
   type_id INTEGER NOT NULL,
   FOREIGN KEY (state_id) REFERENCES service.states (id),
   FOREIGN KEY (type_id) REFERENCES service.types (id)
);

CREATE TABLE service.types (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   min_amount DOUBLE PRECISION NOT NULL,
   max_amount DOUBLE PRECISION NOT NULL,
   interest_rate DOUBLE PRECISION NOT NULL,
   automatic_validation BOOLEAN DEFAULT FALSE
);

INSERT INTO service.types (name, min_amount, max_amount, interest_rate, automatic_validation) VALUES
    ('Microcrédito',     100.00,  5000.00,  2.5, TRUE),
    ('Préstamo Personal', 1000.00, 20000.00, 4.0, FALSE),
    ('Préstamo Hipotecario', 20000.00, 300000.00, 1.5, FALSE),
    ('Préstamo Vehículo', 5000.00, 50000.00, 3.2, TRUE),
    ('Crédito Empresarial', 10000.00, 1000000.00, 5.0, FALSE),
    ('Línea Rápida', 500.00, 3000.00, 6.0, TRUE);

CREATE TABLE service.states (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   description VARCHAR(255)
);

INSERT INTO service.states (name, description) VALUES
    ('Pendiente de revisión', 'La solicitud está esperando revisión inicial'),
    ('En Proceso', 'La solicitud está siendo gestionada por el sistema'),
    ('Aprobada', 'La solicitud ha sido aprobada exitosamente'),
    ('Rechazada', 'La solicitud fue procesada y rechazada'),
    ('Cancelada', 'La solicitud ha sido cancelada por el cliente'),
    ('Completada', 'El proceso de la solicitud finalizó correctamente');
